onlyPlayers: "&7[&aBL&7] &8» &7Only players can use this &acommand&7!"
explosionDone: "&7[&aBL&7] &8» &7Explosion done &asuccessfully&7!"
cmdUsage: "&7[&aBL&7] &8» &7Please use: &a/boomlook"
dontHavePermission: "&7[&aBL&7] &8» &7You don't have &apermission&7!"